# Copyright (c) 2020-2022 The MathWorks, Inc

# Workflow to test MATLAB-Proxy while releasing to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  call-run-tests:
    # Call workflow for running node and python tests
    uses: ./.github/workflows/run-tests.yml

  build_and_publish_pypi:
    needs: call-run-tests
    if: success()
    # windows container is not required here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.sha}}

      - name: Build and Publish in PyPi
        uses: ./.github/actions/build_and_publish_pypi
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

  # build_and_publish_anaconda:
  #   needs: [build_and_publish_pypi]
  #   if: success()
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{github.sha}}

  #     - name: Set up Python 3.6
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.6

  #     - name: Install Python build dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install wheel
  #         python -m pip install .[dev]

  #     - name: Build and Publish to Anaconda.
  #       env:
  #         ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}

  #       run: |
  #         #  $CONDA is an environment variable pointing to the root of the miniconda directory
  #         echo $CONDA/bin >> $GITHUB_PATH
  #         conda install -y conda-build
  #         conda install -y anaconda-client
  #         cd ./anaconda
  #         conda skeleton pypi matlab-proxy
  #         python parse_meta_file.py
  #         conda build ./matlab-proxy --python 3.6 --output-folder ./build
  #         $CONDA/bin/anaconda upload --label main ./build/linux-64/matlab*.tar.gz
