# Copyright (c) 2020-2022 The MathWorks, Inc

# Workflow to test MATLAB-Proxy while releasing to GitHub
name: Testing MATLAB Proxy in Main Branch

on:
  # Trigger workflow both manually and pushing to main
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  call-run-tests:
    # Runs node and python tests
    uses: ./.github/workflows/run-tests.yml

  generate-code-coverage:
    # Generates Code coverage and uploads it
    needs: call-run-tests
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage